// <auto-generated />
using System;
using API_per_il_monitoraggio_delle_api_mellifere.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_per_il_monitoraggio_delle_api_mellifere.Migrations
{
    [DbContext(typeof(ContestoApiario))]
    partial class ContestoApiarioModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_per_il_monitoraggio_delle_api_mellifere.Models.Alveare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttivitaApi")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Posizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<DateTime>("UltimoAggiornamento")
                        .HasColumnType("datetime2");

                    b.Property<double>("Umidita")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Alveari");
                });
#pragma warning restore 612, 618
        }
    }
}
